CREATE TABLE [Content](
	[Id] INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[dealNumber] NVARCHAR(30) NOT NULL,
	[sellerName] NVARCHAR(200) NOT NULL,
	[sellerInn] NVARCHAR(20) NOT NULL,
	[buyerName] NVARCHAR(200) NOT NULL,
	[buyerInn] NVARCHAR(20) NULL,
	[dealDate] DATE NOT NULL,
	[woodVolumeSeller] NVARCHAR(30) NOT NULL,
	[woodVolumeBuyer] NVARCHAR(30) NOT NULL
)